export const properties = {
  $id: "#/properties/properties",
  type: "object",
  title: "Properties",
  description: "Stores the metadata of the study",
  default: {},
  examples: [
    {
      study_name: "Research Study",
      study_id: "RS2023XYZ",
      created_by: "Jane Doe",
      instructions: "Thank you for participating in our research study!",
      post_url: "https://researchstudy.com/api/v1/response",
      empty_msg: "You have completed all tasks.",
      banner_url: "https://researchstudy.com/images/banner.jpg",
      support_url: "https://researchstudy.com/support",
      support_email: "support@researchstudy.com",
      conditions: ["Control Group", "Experimental Group"],
      cache: false,
      ethics: "This study has been approved by the ethics committee under approval #RS2023ETHICS",
      pls: "https://researchstudy.com/pls-file-link.pdf",
    },
  ],
  required: [
    "study_name",
    "study_id",
    "created_by",
    "post_url",
    "empty_msg",
    "banner_url",
    "conditions",
    "cache",
  ],
  properties: {
    study_name: {
      $id: "#/properties/properties/properties/study_name",
      type: "string",
      title: "Name",
      description: "The name of the current study.",
      default: "",
      minLength: 3,
      examples: ["Research Study"],
    },
    study_id: {
      $id: "#/properties/properties/properties/study_id",
      type: "string",
      pattern: "^[a-zA-Z0-9_]+$",
      title: "ID",
      description: "An identifier for the study which is sent to the server with response data.",
      default: "",
      minLength: 3,
      examples: ["RS2023XYZ"],
    },
    created_by: {
      $id: "#/properties/properties/properties/created_by",
      type: "string",
      title: "Created by",
      description: "The name of the creator or author of the study.",
      default: "",
      minLength: 3,
      examples: ["Jane Doe"],
    },
    instructions: {
      $id: "#/properties/properties/properties/instructions",
      type: "string",
      title: "Instructions",
      description: "Brief instructions for participants in the study.",
      default: "",
      minLength: 3,
      examples: ["Thank you for participating in our research study!"],
    },
    post_url: {
      $id: "#/properties/properties/properties/post_url",
      type: "string",
      title: "Post URL",
      description: "URL where participant responses are sent.",
      default: "https://researchstudy.com/api/v1/response",
    },
    empty_msg: {
      $id: "#/properties/properties/properties/empty_msg",
      type: "string",
      title: "Empty Message",
      description: "Message shown when no tasks are available.",
      default: "",
      minLength: 3,
      examples: ["You have completed all tasks."],
    },
    banner_url: {
      $id: "#/properties/properties/properties/banner_url",
      type: "string",
      title: "Banner URL",
      description: "URL of an image displayed in the study app.",
      default: "",
      minLength: 3,
      examples: ["https://researchstudy.com/images/banner.jpg"],
    },
    support_url: {
      $id: "#/properties/properties/properties/support_url",
      type: "string",
      title: "Support URL",
      description: "URL for study support or homepage.",
      default: "",
      minLength: 3,
      examples: ["https://researchstudy.com/support"],
    },
    support_email: {
      $id: "#/properties/properties/properties/support_email",
      type: "string",
      title: "Support Email",
      description: "Email for participant support.",
      default: "",
      minLength: 3,
      examples: ["support@researchstudy.com"],
    },
    cache: {
      $id: "#/properties/properties/properties/cache",
      type: "boolean",
      title: "Cache Media?",
      description: "Indicates if media is cached for offline use.",
      default: true,
    },
    ethics: {
      $id: "#/properties/properties/properties/ethics",
      type: "string",
      title: "Ethics Statement",
      description: "Statement about study ethics.",
      default: "",
      minLength: 3,
      examples: ["This study has been approved by the ethics committee."],
    },
    pls: {
      $id: "#/properties/properties/properties/pls",
      type: "string",
      title: "Plain Language Statement",
      description: "URL to a PDF with the Plain Language Statement.",
      default: "",
      minLength: 3,
      examples: ["https://researchstudy.com/pls-file-link.pdf"],
    },
    conditions: {
      $id: "#/properties/properties/properties/conditions",
      type: "array",
      title: "Conditions",
      description: "List of conditions participants can be assigned to.",
      default: ["Control Group", "Experimental Group"],
      examples: [["Control Group", "Experimental Group"]],
      items: {
        $id: "#/properties/properties/properties/conditions/items",
        type: "string",
        minLength: 1,
      },
    },
  },
};
