FROM nodered/node-red

RUN npm install node-red-contrib-chatbot --unsafe-perm --no-update-notifier --no-fund --only=production
RUN npm install node-red-contrib-chatbot-mission-control --unsafe-perm --no-update-notifier --no-fund --only=production