name: Test building for production
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up --build -d"
