name: Run tests in the project
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server
      - run: npm install
      - run: npm run test
