name: Run tests in the project
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd server
          npm install
          npm run test
      - run: |
          cd redcap
          python3 -m venv venv
          . venv/bin/activate 
          python3 -m pip install -r requirements.txt
          python3 -m pip install -U pytest
          pytest server_test.py
